-- sql/024-product-content-images.sql
-- Rich content, real images, local SEO keywords, and Hydrinity catalog fix
-- Run AFTER 023-product-seed.sql has been applied

-- ============================================================
-- SKINBETTER SCIENCE — Image + Content Updates
-- ============================================================

-- 1. AlphaRet Overnight Cream (already has good content, update image + enrich)
UPDATE products SET
  image_url = '/images/products/skinbetter/alpharet-cream.jpg',
  price = 165.00,
  size = '50ml / 1.7 fl oz'
WHERE slug = 'alpharet-overnight-cream';

-- 2. AlphaRet Exfoliating Peel Pads
UPDATE products SET
  image_url = '/images/products/skinbetter/peel-pads.jpg',
  price = 95.00,
  size = '30 pads',
  description = 'AlphaRet® Exfoliating Peel Pads are a convenient at-home chemical peel by skinbetter science that deliver professional-grade exfoliation in a single pre-soaked pad. Each pad combines glycolic acid, lactic acid, and salicylic acid with skinbetter''s patented AlphaRet technology—providing multi-acid resurfacing with built-in retinoid benefits. The result is immediate brightening and texture refinement that typically requires an in-office peel. Available at RELUXE Med Spa in Westfield and Carmel, Indiana.

These peel pads are a game-changer for patients who want visible smoothing between clinic visits. Use them 1-2 times per week for an instant glow before events, or as a regular texture-refining step in your evening routine. The triple-acid formula exfoliates at the surface (glycolic), mid-level (lactic), and within pores (salicylic), while AlphaRet stimulates cell turnover underneath. Our Hamilton County patients love keeping a jar at home for pre-event radiance and weekly maintenance between microneedling or laser sessions at RELUXE.',
  faq = '[{"q":"How often should I use the peel pads?","a":"Start with once per week in the evening. If your skin tolerates it well after 2-3 weeks, you can increase to twice weekly. Do not use on the same night as AlphaRet Overnight Cream."},{"q":"Can I use these with my AlphaRet Overnight Cream?","a":"Yes, but on alternate nights. Use peel pads 1-2 times per week and AlphaRet Overnight Cream on the other nights. Your RELUXE provider in Westfield or Carmel can help build the right schedule for your skin."},{"q":"Are these good before events or special occasions?","a":"Absolutely—that''s one of their best uses. Use a pad the night before a wedding, date night, or photo event for instant brightening and smoothing. Our Carmel and Westfield patients call them their event-prep secret."},{"q":"Where can I buy AlphaRet Peel Pads near me in Indiana?","a":"AlphaRet Exfoliating Peel Pads are available through our authorized skinbetter science store and at both RELUXE Med Spa locations in Westfield and Carmel, Indiana."}]'::JSONB,
  staff_picks = '{"westfield":"Our Westfield team''s event-prep secret—one pad the night before delivers an instant glow that patients across Hamilton County swear by.","carmel":"The easiest active in any routine. Carmel patients love these for weekly texture maintenance between microneedling and laser sessions at RELUXE."}'::JSONB,
  related_services = ARRAY['microneedling', 'chemical-peels']
WHERE slug = 'alpharet-peel-pads';

-- 3. Alto Advanced Defense and Repair Serum
UPDATE products SET
  image_url = '/images/products/skinbetter/alto.jpg',
  price = 175.00,
  size = '30ml / 1 fl oz',
  description = 'Alto Advanced Defense and Repair Serum is a broad-spectrum antioxidant treatment by skinbetter science that provides comprehensive environmental protection for your skin every morning. Combining 19 powerful antioxidants including vitamin C, vitamin E, and the rare Lipochroman compound, Alto defends against UV-induced free radical damage, visible light, infrared radiation, and pollution. This is the AM counterpart to the AlphaRet PM protocol—together they form one of the most effective anti-aging programs in professional skincare. Available at RELUXE Med Spa in Westfield and Carmel, Indiana.

What makes Alto Advanced unique is its multi-pathway approach to antioxidant protection. Rather than relying on a single ingredient, the formula combines fat-soluble and water-soluble antioxidants that work in different cellular compartments, providing overlapping defense at every level. Lipochroman is particularly notable—it protects against both reactive oxygen and nitrogen species, a capability few other antioxidants offer. For patients in Hamilton County dealing with Indiana''s variable climate—intense summer UV, winter wind, and seasonal shifts—Alto provides the daily environmental shield your skin needs year-round.',
  faq = '[{"q":"When should I apply Alto Advanced?","a":"Every morning after cleansing, before your SPF. Apply 2-3 pumps to face, neck, and chest. Allow 30 seconds to absorb, then apply your Colorescience Face Shield or mineral sunscreen over it."},{"q":"Can I use Alto with other vitamin C serums?","a":"Alto is designed as a complete antioxidant system—you don''t need additional vitamin C when using it. If you also use SkinCeuticals CE Ferulic, alternate days or use one AM and consult your RELUXE provider for the ideal protocol."},{"q":"What makes Alto different from basic vitamin C serums?","a":"Alto contains 19 antioxidants including Lipochroman, which protects against reactive nitrogen species that standard vitamin C cannot address. It provides broader defense against UV, visible light, infrared, and pollution—not just free radicals from UV alone."},{"q":"Where can I buy Alto Advanced near me in Indiana?","a":"Alto Advanced Defense and Repair Serum is available through our authorized skinbetter science store and at both RELUXE Med Spa locations—Westfield and Carmel, Indiana."}]'::JSONB,
  staff_picks = '{"westfield":"Your morning defense layer. Our Westfield team pairs Alto AM with AlphaRet PM for the gold-standard anti-aging protocol—patients across Hamilton County see dramatic improvement in firmness and glow.","carmel":"The Carmel team''s most-recommended morning serum. Layers under Colorescience SPF for complete environmental defense whether you''re walking the Monon Trail or at your desk."}'::JSONB,
  related_services = ARRAY['microneedling', 'chemical-peels', 'laser-resurfacing']
WHERE slug = 'alto-advanced';

-- 4. InterFuse Treatment Cream EYE
UPDATE products SET
  image_url = '/images/products/skinbetter/interfuse-eye.jpg',
  price = 120.00,
  size = '15ml / 0.5 fl oz',
  description = 'InterFuse® Treatment Cream EYE is a peptide-rich eye treatment by skinbetter science that targets every major sign of aging around the delicate peri-orbital area—fine lines, crepiness, puffiness, and dark circles. The proprietary InterFuse delivery system uses encapsulated technology to enhance penetration of active peptides and retinol into skin that''s notoriously difficult to treat. This is the eye treatment our RELUXE injectors recommend between Botox and filler appointments. Available at RELUXE Med Spa in Westfield and Carmel, Indiana.

The eye area ages faster than any other zone on the face because the skin is up to 10x thinner, produces less oil, and endures constant movement from blinking and expressions. InterFuse EYE was designed specifically for these challenges. The peptide complex stimulates collagen in this thin tissue while caffeine addresses puffiness and dark circles. Niacinamide strengthens the barrier, and microencapsulated retinol works beneath the surface to smooth texture. For our Hamilton County patients using neuromodulators, this product extends the visible benefits of Botox between appointments—maintaining smoothness and brightness in the crow''s feet and under-eye area daily.',
  faq = '[{"q":"Can I use InterFuse EYE with Botox?","a":"Yes—it''s one of the best daily complements to neuromodulator treatments. InterFuse EYE maintains smoothness and brightness between Botox appointments. Our RELUXE injectors in Westfield and Carmel recommend it to all their eye-area patients."},{"q":"Is InterFuse EYE safe for sensitive eyes?","a":"The formula is ophthalmologist tested and specifically designed for the delicate peri-orbital area. Apply along the orbital bone with your ring finger using gentle patting motions—never drag or pull."},{"q":"How does the InterFuse delivery system work?","a":"InterFuse uses encapsulated technology to deliver active peptides and retinol deeper into the thin eye-area skin than standard formulas can achieve. The microencapsulation also reduces irritation by releasing ingredients gradually."},{"q":"Where can I get professional eye treatments near me in Hamilton County?","a":"RELUXE Med Spa offers comprehensive eye-area treatments at both our Westfield and Carmel locations—including Botox, filler, and medical-grade skincare like InterFuse EYE. Book a consultation to build your personalized eye protocol."}]'::JSONB,
  staff_picks = '{"westfield":"Our Westfield injectors'' favorite eye product. Extends the benefits of Botox between appointments—patients who add InterFuse EYE consistently look fresher longer.","carmel":"The Carmel team''s go-to for anyone concerned about the eye area. Peptides + retinol + caffeine in one elegant formula that plays perfectly with injectable treatments at RELUXE."}'::JSONB,
  related_services = ARRAY['botox', 'filler', 'microneedling']
WHERE slug = 'interfuse-eye';

-- 5. Trio Rebalancing Moisture Treatment
UPDATE products SET
  image_url = '/images/products/skinbetter/trio.jpg',
  price = 125.00,
  size = '50ml / 1.7 fl oz',
  description = 'Trio Rebalancing Moisture Treatment is a lightweight yet effective barrier-support moisturizer by skinbetter science that combines ceramides, essential fatty acids, and cholesterol in a biomimetic ratio that mirrors the skin''s natural lipid composition. Unlike heavy creams that can clog pores or interfere with active ingredients, Trio provides the hydration and barrier protection your skin needs without compromising the performance of retinoids, acids, or vitamin C underneath. Available at RELUXE Med Spa in Westfield and Carmel, Indiana.

Trio is the glue that holds an active skincare routine together. When patients start potent ingredients like AlphaRet or chemical exfoliants, the skin barrier needs support—and Trio provides exactly that without heaviness or shine. It''s one of the few moisturizers that works beautifully across all skin types, from dry winter skin in Indiana to oily summer skin during Hamilton County''s humid months. Our RELUXE clinicians use it as the buffer during retinoid introduction: layered over AlphaRet on the first few nights, it reduces irritation without diminishing the retinoid''s effectiveness.',
  faq = '[{"q":"Is Trio heavy or greasy?","a":"No—despite being a barrier-repair moisturizer, Trio has a lightweight, fast-absorbing texture. It works for all skin types including oily and acne-prone skin without causing congestion or shine."},{"q":"Can I use Trio with AlphaRet Overnight Cream?","a":"Absolutely—that''s one of its best uses. Layer Trio over AlphaRet when you''re first starting or when your skin feels sensitive. It buffers irritation without reducing the retinoid''s effectiveness."},{"q":"Do I need this if my skin isn''t dry?","a":"Yes. Trio isn''t just for dry skin—it''s barrier support. Even oily and combination skin types need barrier protection, especially when using active ingredients like retinoids, acids, or vitamin C. It helps your actives work better."},{"q":"Where can I buy skinbetter science near me in Westfield or Carmel?","a":"Trio Rebalancing Moisture Treatment and the full skinbetter science line are available at both RELUXE Med Spa locations in Westfield and Carmel, Indiana. Shop online or visit us for a complimentary skin consultation."}]'::JSONB,
  staff_picks = '{"westfield":"The unsung hero of every skincare routine at our Westfield clinic. Trio makes retinoid introduction comfortable and keeps barrier function strong through Indiana''s harsh seasonal swings.","carmel":"Our Carmel team recommends Trio to every patient starting AlphaRet—it''s the moisturizer that makes active ingredients tolerable and effective. Lightweight enough for Hamilton County summers, supportive enough for winter."}'::JSONB,
  related_services = ARRAY['microneedling', 'chemical-peels', 'laser-resurfacing']
WHERE slug = 'trio-rebalancing-moisture';

-- 6. Even Tone Correcting Serum
UPDATE products SET
  image_url = '/images/products/skinbetter/even-tone.jpg',
  price = 165.00,
  size = '50ml / 1.7 fl oz',
  description = 'Even Tone Correcting Serum is a multi-pathway brightening treatment by skinbetter science that targets visible discoloration, dark spots, melasma maintenance, and overall dullness. The formula uses arbutin, niacinamide, hexylresorcinol, and phytic acid to interrupt melanin production at multiple stages—a comprehensive approach that delivers visible brightening without the irritation of hydroquinone. Available at RELUXE Med Spa in Westfield and Carmel, Indiana.

Pigmentation is one of the most common concerns our Hamilton County patients bring to RELUXE, and Even Tone is a cornerstone of our at-home pigment protocols. Indiana''s seasonal UV exposure—especially the strong summer sun—can trigger and worsen melasma, sun spots, and post-inflammatory hyperpigmentation. Even Tone provides daily pigment suppression that compounds over time, especially when paired with consistent mineral SPF and periodic in-clinic treatments like IPL, chemical peels, or laser resurfacing. The serum layers beautifully under other skinbetter products and can be used alongside AlphaRet for a complete evening anti-aging + brightening routine.',
  faq = '[{"q":"How long until I see brightening results?","a":"Most patients notice visible improvement in overall radiance within 2-3 weeks. Significant reduction in dark spots and discoloration typically occurs at the 6-8 week mark with consistent daily use."},{"q":"Is Even Tone safe for melasma patients?","a":"Yes—it''s specifically designed for melasma maintenance. The multi-pathway formula avoids hydroquinone while still delivering meaningful pigment correction. Pair with daily mineral SPF and periodic in-clinic treatments at RELUXE for best results."},{"q":"Can I layer Even Tone with AlphaRet?","a":"Yes. Apply Even Tone first, allow it to absorb, then apply AlphaRet Overnight Cream. This combination addresses both pigmentation and texture simultaneously—it''s one of the most effective evening protocols our RELUXE clinicians recommend."},{"q":"Where can I get melasma treatment near me in Hamilton County?","a":"RELUXE Med Spa offers comprehensive melasma management at both our Westfield and Carmel locations. Even Tone is part of our at-home melasma protocol, paired with mineral SPF, in-clinic IPL, chemical peels, and SkinCeuticals Discoloration Defense for a multi-product approach."}]'::JSONB,
  staff_picks = '{"westfield":"Our Westfield team''s top pick for pigment-prone patients. Even Tone + daily mineral SPF + periodic IPL at RELUXE is the gold-standard melasma protocol across Hamilton County.","carmel":"Melasma-friendly maintenance that compounds over time. The Carmel team layers it under AlphaRet for a one-two punch of brightening and anti-aging that patients see and feel."}'::JSONB,
  related_services = ARRAY['ipl-photofacial', 'chemical-peels', 'laser-resurfacing']
WHERE slug = 'even-tone-correcting-serum';


-- ============================================================
-- SKINCEUTICALS — Image + Content Updates
-- ============================================================

-- 1. CE Ferulic
UPDATE products SET
  image_url = '/images/products/skinceuticals/ce-ferulic.jpg',
  price = 182.00,
  size = '30ml / 1 fl oz',
  description = 'CE Ferulic® is the gold-standard antioxidant serum by SkinCeuticals, combining 15% pure L-ascorbic acid (vitamin C), 1% alpha tocopherol (vitamin E), and 0.5% ferulic acid in a patented formula that delivers 8 times the skin''s natural photoprotection against environmental damage. CE Ferulic is the most-studied and most-recommended vitamin C serum in dermatology, with over two decades of published clinical research proving its ability to reduce oxidative stress, brighten the complexion, firm the skin, and diminish the appearance of fine lines and wrinkles. Available exclusively at RELUXE Med Spa in Westfield and Carmel, Indiana.

The synergy between vitamins C, E, and ferulic acid is what makes CE Ferulic extraordinary. The Duke University-patented combination not only stabilizes vitamin C for maximum potency but also amplifies its photoprotective effects exponentially. Applied every morning before SPF, CE Ferulic creates an invisible antioxidant shield that neutralizes free radicals from UV exposure, pollution, and blue light throughout the day. The result is visible brightening within weeks, measurable firming over months, and long-term protection against photoaging. For our Hamilton County patients, CE Ferulic is the single most impactful product they can add to a morning routine—it''s the foundation on which great skin is built.',
  faq = '[{"q":"Why is CE Ferulic so expensive compared to other vitamin C serums?","a":"CE Ferulic uses patented technology that took years to develop. The specific combination of 15% L-ascorbic acid at pH 2.0-3.5, 1% vitamin E, and 0.5% ferulic acid creates exponential synergy—8x more photoprotection than vitamin C alone. Drugstore vitamin C serums cannot replicate this stability or efficacy."},{"q":"Why does CE Ferulic have that smell?","a":"The slight hot-dog-like scent comes from pure L-ascorbic acid at therapeutic concentration. It indicates potency, not spoilage. The scent dissipates within seconds of application and does not affect performance."},{"q":"Can I buy CE Ferulic online?","a":"SkinCeuticals is a professional-only brand. CE Ferulic is available exclusively through authorized providers like RELUXE Med Spa. Visit our Westfield or Carmel location for a complimentary skin consultation and purchase."},{"q":"How long does one bottle of CE Ferulic last?","a":"With daily use of 4-5 drops each morning, one 30ml bottle lasts approximately 2-3 months. Store in a cool, dark place—CE Ferulic should remain golden or light amber in color."}]'::JSONB,
  staff_picks = '{"westfield":"The single most impactful addition to any skincare routine. Our Westfield team has seen CE Ferulic transform dull, aging skin across Hamilton County—it''s the product we''d keep if we could only keep one.","carmel":"Every skincare routine at RELUXE Carmel starts with CE Ferulic. Apply before your Colorescience SPF every morning—it''s 8x more photoprotection than vitamin C alone. The gold standard for Indiana patients serious about their skin."}'::JSONB,
  related_services = ARRAY['microneedling', 'chemical-peels', 'ipl-photofacial']
WHERE slug = 'ce-ferulic';

-- 2. Phloretin CF
UPDATE products SET
  image_url = '/images/products/skinceuticals/phloretin.jpg',
  price = 182.00,
  size = '30ml / 1 fl oz',
  description = 'Phloretin CF® is a brightening antioxidant serum by SkinCeuticals formulated specifically for combination and oily skin types. The patented formula combines 2% phloretin, 10% L-ascorbic acid, and 0.5% ferulic acid to provide environmental protection while simultaneously addressing discoloration, uneven tone, and fine lines. Where CE Ferulic is the gold standard for dry-to-normal skin, Phloretin CF is the gold standard for combination and oily skin—delivering comparable antioxidant power with a lighter, oil-friendly texture. Available exclusively at RELUXE Med Spa in Westfield and Carmel, Indiana.

Phloretin is a naturally occurring antioxidant found in apple seeds that provides unique skin-brightening benefits beyond standard vitamin C. It inhibits melanin transport to the skin surface, making it particularly effective for patients dealing with post-inflammatory hyperpigmentation, sun spots, and melasma alongside oily or combination skin. The lightweight fluid texture absorbs quickly without adding shine or congestion—critical for patients who struggle with midday oiliness in Indiana''s humid summers. Our RELUXE clinicians recommend Phloretin CF for any combination-skin patient who wants the antioxidant power of CE Ferulic without the richer texture.',
  faq = '[{"q":"Should I use CE Ferulic or Phloretin CF?","a":"If your skin is dry or normal, CE Ferulic is ideal. If your skin is combination or oily, Phloretin CF is your match. Both provide powerful antioxidant protection—the difference is texture and secondary benefits. Your RELUXE provider in Westfield or Carmel can help you choose during a complimentary consultation."},{"q":"Does Phloretin CF help with dark spots?","a":"Yes—phloretin actively inhibits melanin transport, making it one of the most effective antioxidant serums for discoloration and uneven tone in oily/combination skin types."},{"q":"Can I use Phloretin CF with other SkinCeuticals products?","a":"Absolutely. Apply Phloretin CF first in the morning, then layer your SPF. In the evening, pair with Discoloration Defense for enhanced brightening or Silymarin CF if you need additional oil control."},{"q":"Where can I buy SkinCeuticals in Westfield or Carmel?","a":"SkinCeuticals is available exclusively at authorized providers. Visit RELUXE Med Spa at our Westfield or Carmel location for the full SkinCeuticals line and a complimentary skin consultation."}]'::JSONB,
  staff_picks = '{"westfield":"Our Westfield team''s vitamin C pick for combination skin patients. Brightens and protects without adding shine—perfect for Hamilton County patients who get oily in summer humidity.","carmel":"Phloretin CF is the Carmel team''s answer for patients who want CE Ferulic''s power but have oily or combination skin. Lighter texture, same-tier protection, plus additional brightening benefits for pigment-prone skin."}'::JSONB,
  related_services = ARRAY['chemical-peels', 'ipl-photofacial', 'microneedling']
WHERE slug = 'phloretin-cf';

-- 3. Silymarin CF
UPDATE products SET
  image_url = '/images/products/skinceuticals/silymarin.jpg',
  price = 172.00,
  size = '30ml / 1 fl oz',
  description = 'Silymarin CF is an antioxidant serum by SkinCeuticals specifically formulated for oily and blemish-prone skin. Combining 0.5% silymarin (milk thistle extract), 15% L-ascorbic acid, 0.5% ferulic acid, and 0.5% salicylic acid, it provides the environmental protection of a vitamin C serum while simultaneously reducing oiliness, refining pores, and preventing acne marks from becoming lasting hyperpigmentation. This is the vitamin C serum that finally works for breakout-prone skin. Available exclusively at RELUXE Med Spa in Westfield and Carmel, Indiana.

For years, oily and acne-prone patients were stuck choosing between antioxidant protection and clear skin—most vitamin C serums either triggered breakouts or felt too heavy. Silymarin CF solved that problem. The oil-free formula absorbs instantly, the salicylic acid keeps pores clear, and silymarin (a potent antioxidant from milk thistle) specifically supports oil-prone skin by improving texture and preventing oxidative damage from sebum. For our Hamilton County patients dealing with adult acne or post-acne marks, Silymarin CF provides the environmental defense their skin needs without any of the drawbacks. It''s also the preferred vitamin C for patients on prescription acne medications—compatible with tretinoin, adapalene, and other topical acne treatments.',
  faq = '[{"q":"Will Silymarin CF break me out?","a":"No—Silymarin CF was specifically formulated for acne-prone skin. The oil-free formula includes salicylic acid to keep pores clear, and clinical studies showed improvement in skin oiliness and texture. It''s the first vitamin C serum designed to work with breakout-prone skin, not against it."},{"q":"Can I use Silymarin CF with my acne medications?","a":"Yes. Silymarin CF is compatible with topical retinoids (tretinoin, adapalene), benzoyl peroxide, and other acne treatments. Apply Silymarin CF in the morning and use acne medications in the evening as directed by your RELUXE provider."},{"q":"How is Silymarin CF different from CE Ferulic?","a":"Both provide powerful antioxidant protection, but Silymarin CF is specifically formulated for oily and blemish-prone skin. It includes salicylic acid for pore refinement and silymarin for oil control—benefits CE Ferulic doesn''t offer. CE Ferulic is better for dry/normal skin; Silymarin CF is the choice for oily/acne-prone."},{"q":"Where can I get acne treatment near me in Indiana?","a":"RELUXE Med Spa offers comprehensive acne treatment at both our Westfield and Carmel locations. Silymarin CF is part of our recommended acne skincare protocol, paired with in-clinic treatments like chemical peels and laser therapy."}]'::JSONB,
  staff_picks = '{"westfield":"Vitamin C for acne-prone skin that actually works. Our Westfield team recommends Silymarin CF to every breakout-prone patient—it protects, brightens, and clears pores without triggering congestion.","carmel":"The Carmel team''s go-to for adult acne patients who also want anti-aging benefits. Silymarin CF provides vitamin C protection without shine, oiliness, or breakouts—game-changer for Hamilton County patients managing acne and aging simultaneously."}'::JSONB,
  related_services = ARRAY['chemical-peels', 'acne-treatment', 'microneedling']
WHERE slug = 'silymarin-cf';

-- 4. Discoloration Defense
UPDATE products SET
  image_url = '/images/products/skinceuticals/discoloration.jpg',
  price = 104.00,
  size = '30ml / 1 fl oz',
  description = 'Discoloration Defense is a multi-pathway pigment-correcting serum by SkinCeuticals that targets stubborn dark spots, post-inflammatory hyperpigmentation, and melasma at multiple stages of melanin production. The formula combines 3% tranexamic acid, 1% kojic acid, 5% niacinamide, and 5% HEPES to inhibit melanin synthesis, reduce melanin transfer, and accelerate cell turnover simultaneously—a comprehensive approach that delivers visible improvement in discoloration where single-ingredient products fail. Available exclusively at RELUXE Med Spa in Westfield and Carmel, Indiana.

Pigment disorders are among the most frustrating skin concerns because they''re triggered by so many factors—UV exposure, hormones, inflammation, and heat. Indiana''s strong summer sun and seasonal shifts make pigmentation especially persistent for Hamilton County residents. Discoloration Defense was formulated to address this complexity with a four-ingredient approach that works at every step of the pigmentation pathway. Tranexamic acid reduces UV-triggered melanin signals. Kojic acid inhibits the tyrosinase enzyme that produces melanin. Niacinamide blocks melanin transfer to the skin surface. HEPES accelerates cell turnover to shed pigmented cells faster. Together, they produce measurable lightening of dark spots within 6-12 weeks—and the improvement compounds with continued use. Our RELUXE providers pair Discoloration Defense with daily mineral SPF, periodic IPL or chemical peels, and Colorescience Even Up for the most complete pigment management protocol available.',
  faq = '[{"q":"How fast will I see results from Discoloration Defense?","a":"Most patients notice visible improvement in overall radiance within 2 weeks. Measurable reduction in stubborn dark spots and hyperpigmentation typically appears at the 6-12 week mark with consistent twice-daily use."},{"q":"Can I use this for melasma treatment?","a":"Yes—Discoloration Defense is one of the cornerstone products in our melasma protocol at RELUXE Med Spa. The tranexamic acid specifically targets hormonal and UV-triggered pigmentation. Pair it with mineral SPF daily and periodic in-clinic treatments for best results."},{"q":"Is it safe for all skin tones?","a":"Yes. Discoloration Defense is safe and effective across all Fitzpatrick skin types. The formula avoids hydroquinone, making it suitable for long-term use without risk of paradoxical darkening that some other lightening agents can cause."},{"q":"Where can I get dark spot treatment near me in Carmel or Westfield?","a":"RELUXE Med Spa offers comprehensive pigment correction at both Hamilton County locations. Discoloration Defense is part of our at-home pigment protocol, paired with in-clinic IPL, chemical peels, and Colorescience Even Up SPF for complete melasma and hyperpigmentation management."}]'::JSONB,
  staff_picks = '{"westfield":"The Westfield team''s #1 pigment corrector. Discoloration Defense + mineral SPF + periodic IPL is our gold-standard melasma protocol for Hamilton County patients who are serious about evening their tone.","carmel":"Our Carmel clinicians pair Discoloration Defense PM with Colorescience Even Up AM for around-the-clock pigment management. It''s the combination that finally moves the needle on stubborn dark spots and melasma."}'::JSONB,
  related_services = ARRAY['ipl-photofacial', 'chemical-peels', 'laser-resurfacing']
WHERE slug = 'discoloration-defense';

-- 5. Triple Lipid Restore 2:4:2
UPDATE products SET
  image_url = '/images/products/skinceuticals/triple-lipid.jpg',
  price = 138.00,
  size = '48ml / 1.6 fl oz',
  description = 'Triple Lipid Restore 2:4:2 is a barrier-repair moisturizer by SkinCeuticals that replenishes the skin''s essential lipids in the optimal ratio proven by research: 2% ceramides, 4% cholesterol, and 2% fatty acids. This lipid-complex formula restores the skin barrier, improves texture, nourishes, and provides deep comfort for compromised, sensitized, or aging skin. Available exclusively at RELUXE Med Spa in Westfield and Carmel, Indiana.

The skin barrier is a lipid matrix that keeps moisture in and irritants out—and it''s the first thing to break down when you start active ingredients, undergo energy-based treatments, or face environmental stress. Indiana''s dramatic seasonal swings—from humid summers to dry, cold winters—put particular strain on barrier function. Triple Lipid Restore was engineered to replenish exactly what a stressed barrier loses: ceramides for structure, cholesterol for fluidity, and fatty acids for softness. This isn''t just a moisturizer—it''s barrier engineering. Our RELUXE clinicians consider it essential (not optional) for patients on retinoid protocols, recovering from laser or microneedling treatments, or experiencing winter-related sensitivity. The rich but non-greasy texture absorbs well and doesn''t interfere with active ingredients, making it an ideal final step in both AM and PM routines.',
  faq = '[{"q":"When should I use Triple Lipid Restore 2:4:2?","a":"Apply morning and evening as the last step of your skincare routine (after serums and treatments). It''s especially important during retinoid introduction, post-procedure recovery, and Indiana''s dry winter months when barrier stress peaks."},{"q":"Is Triple Lipid Restore heavy or greasy?","a":"Despite being a lipid-rich cream, it absorbs well and doesn''t feel heavy or greasy. The 2:4:2 ratio is bioidentical to the skin''s own lipid composition, so it integrates naturally rather than sitting on top."},{"q":"Do I need this if I already use a moisturizer?","a":"Triple Lipid Restore isn''t a basic moisturizer—it''s targeted barrier repair. If you''re using active ingredients like retinoids, acids, or vitamin C, or recovering from treatments at RELUXE, your barrier needs lipid replenishment that standard moisturizers don''t provide."},{"q":"Where can I buy SkinCeuticals Triple Lipid near me?","a":"Triple Lipid Restore 2:4:2 is available exclusively at authorized providers like RELUXE Med Spa in Westfield and Carmel, Indiana. Visit either Hamilton County location for the full SkinCeuticals line."}]'::JSONB,
  staff_picks = '{"westfield":"Essential barrier support at our Westfield clinic. Triple Lipid makes retinoid introduction comfortable and keeps skin resilient through Indiana''s brutal winter-to-summer transitions. Not optional—necessary.","carmel":"The Carmel team prescribes Triple Lipid to every patient on retinoids or recovering from laser and microneedling at RELUXE. It''s barrier engineering in a jar—the moisturizer that makes everything else work better."}'::JSONB,
  related_services = ARRAY['microneedling', 'laser-resurfacing', 'chemical-peels']
WHERE slug = 'triple-lipid-restore';

-- 6. Glycolic 10 Renew Overnight
UPDATE products SET
  image_url = '/images/products/skinceuticals/glycolic.jpg',
  price = 80.00,
  size = '50ml / 1.7 fl oz',
  description = 'Glycolic 10 Renew Overnight is a night treatment by SkinCeuticals that uses 10% glycolic acid in a time-release formula to refine skin texture, reduce roughness, and improve radiance while you sleep. Unlike leave-on peels that can irritate, the sustained-release technology delivers glycolic acid gradually throughout the night, minimizing irritation while maximizing the exfoliating and brightening benefits. A soothing complex buffers the acid for comfortable nightly use. Available exclusively at RELUXE Med Spa in Westfield and Carmel, Indiana.

Glycolic acid is the smallest alpha hydroxy acid molecule, allowing it to penetrate effectively and dissolve the bonds between dead skin cells that cause dullness, roughness, and uneven texture. Glycolic 10 Renew Overnight harnesses this power in a gentle nightly format that''s ideal for patients who can''t tolerate retinoids or want to add an exfoliating step to complement their retinoid routine. Indiana''s seasonal dryness—especially in winter—can cause surface buildup that makes skin look dull and rough. This treatment addresses that directly, revealing smoother, brighter skin by morning. Our RELUXE clinicians often recommend it as an alternative evening active for patients who experience too much irritation from retinoids, or as a 2-3 times per week addition to an AlphaRet or tretinoin routine.',
  faq = '[{"q":"Can I use Glycolic 10 with a retinoid like AlphaRet?","a":"Yes, but on alternate nights. Use Glycolic 10 Renew Overnight 2-3 times per week and your retinoid on the other nights. Your RELUXE provider in Westfield or Carmel can help build the ideal schedule for your skin."},{"q":"Is this gentler than an in-clinic chemical peel?","a":"Yes. Glycolic 10 Renew Overnight uses time-release technology that delivers glycolic acid gradually, plus a built-in soothing complex. It provides consistent, gentle exfoliation rather than the concentrated single-session approach of an in-clinic peel. Both have their place—talk to your RELUXE provider about the right combination."},{"q":"How quickly will I see smoother skin?","a":"Most patients notice smoother texture and improved radiance within 1-2 weeks of consistent use. Start 2-3 times per week and increase to nightly as tolerated."},{"q":"Who is this best for?","a":"Patients with dull, rough-textured skin who want gentle nightly exfoliation. It''s also excellent for patients who can''t tolerate retinoids, or as a complement to retinoid therapy on alternating nights. Especially popular among our Hamilton County patients during Indiana''s dry winter months."}]'::JSONB,
  staff_picks = '{"westfield":"Our Westfield team''s retinoid alternative for sensitive patients. Glycolic 10 delivers nightly texture refinement without the irritation—perfect for patients easing into an active skincare routine.","carmel":"The Carmel team loves pairing Glycolic 10 with AlphaRet on alternating nights. Two different exfoliation pathways, maximum smoothing, and the time-release formula keeps irritation minimal even in Indiana''s dry winters."}'::JSONB,
  related_services = ARRAY['chemical-peels', 'microneedling']
WHERE slug = 'glycolic-10-renew-overnight';


-- ============================================================
-- HYDRINITY — Fix Product Catalog + Rich Content
-- ============================================================

-- 1. Restorative HA Serum (name matches, update content)
UPDATE products SET
  image_url = '/images/products/hydrinity/ha-serum.jpg',
  price = 120.00,
  size = '30ml / 1 fl oz',
  subtitle = 'Multi-Weight HA Recovery Serum',
  short_description = 'Multi-weight hyaluronic acid serum that delivers deep hydration for post-procedure, dehydrated, and compromised skin.',
  description = 'Restorative HA Serum is a multi-weight hyaluronic acid treatment by Hydrinity that delivers deep, sustained hydration for compromised, dehydrated, and post-procedure skin. The formula uses multiple molecular weights of hyaluronic acid—large molecules create a moisture-locking film on the surface, medium molecules plump the mid-layers, and small molecules penetrate deep to hydrate from within. Combined with peptides and aloe vera, it accelerates healing and restores comfort after energy-based treatments. Available at RELUXE Med Spa in Westfield and Carmel, Indiana.

Restorative HA Serum is the first product our providers reach for after microneedling, laser resurfacing, and chemical peels at both RELUXE locations. The gentle, fragrance-free formula delivers immediate comfort on contact and sustained hydration over 24 hours. For patients not recovering from procedures, it''s equally powerful as a daily hydration booster during Indiana''s dry winter months or for anyone whose skin feels chronically dehydrated. Layer it under any moisturizer—from Trio Rebalancing Moisture by skinbetter to Triple Lipid Restore by SkinCeuticals—to amplify hydration at every level.',
  key_ingredients = ARRAY['Multi-Weight Hyaluronic Acid', 'Peptides', 'Aloe Vera', 'Panthenol'],
  faq = '[{"q":"When should I use Restorative HA Serum after a procedure?","a":"Your RELUXE provider will typically recommend starting Restorative HA Serum immediately after or within 24 hours of microneedling, laser, or chemical peel treatments. It''s one of the first products that''s safe on freshly treated skin."},{"q":"Can I use this daily even without a procedure?","a":"Absolutely. Restorative HA Serum is an excellent daily hydration booster for anyone with dehydrated skin. It''s especially popular during Indiana''s dry winter months among our Westfield and Carmel patients."},{"q":"How is this different from regular hyaluronic acid serums?","a":"Restorative HA Serum uses multiple molecular weights of hyaluronic acid that work at different depths—surface, mid-layer, and deep. Most drugstore HA serums use only one molecular weight. The multi-weight approach delivers both immediate comfort and sustained hydration."},{"q":"Where can I get post-procedure skincare near me in Hamilton County?","a":"RELUXE Med Spa carries the full Hydrinity recovery line at both our Westfield and Carmel locations. We''ll send you home with the right post-procedure products after every treatment."}]'::JSONB,
  staff_picks = '{"westfield":"The first product our Westfield team reaches for after every microneedling and laser treatment. Multi-weight HA delivers immediate comfort and sustained hydration—patients feel the difference instantly.","carmel":"Our Carmel team''s go-to post-procedure serum. Restorative HA keeps healing skin hydrated and comfortable through recovery, and doubles as a daily hydration powerhouse during Indiana''s dry winters."}'::JSONB,
  related_services = ARRAY['microneedling', 'laser-resurfacing', 'chemical-peels']
WHERE slug = 'restorative-ha-serum';

-- 2. Soothing Recovery Gel → HYACYN ACTIVE
UPDATE products SET
  slug = 'hyacyn-active',
  name = 'HYACYN ACTIVE Purifying Mist',
  subtitle = 'Hypochlorous Acid Post-Procedure Spray',
  short_description = 'Hypochlorous acid purifying mist that cleanses, calms, and protects post-procedure skin without disrupting healing.',
  description = 'HYACYN ACTIVE is a hypochlorous acid (HOCl) purifying mist by Hydrinity that provides gentle antimicrobial cleansing and calming for post-procedure, sensitive, and reactive skin. Hypochlorous acid is the same molecule your immune system naturally produces to fight bacteria and reduce inflammation—HYACYN ACTIVE delivers it in a convenient spray format that cleanses without disrupting the skin barrier or healing process. Available at RELUXE Med Spa in Westfield and Carmel, Indiana.

HYACYN ACTIVE has become a post-procedure staple at both RELUXE locations. After microneedling, laser resurfacing, or chemical peels, traditional cleansers can be too harsh for freshly treated skin—but the treated area still needs gentle cleansing to prevent infection and support healing. HYACYN ACTIVE fills that gap perfectly: spray it on, let it air dry, and it provides antimicrobial protection without any rubbing, rinsing, or irritation. Our providers also recommend it for patients with acne, rosacea, and chronic skin sensitivity as a daily calming mist. Keep it in the refrigerator for extra soothing relief on hot, reactive skin.',
  category = 'hydration',
  image_url = '/images/products/hydrinity/hyacyn-active.jpg',
  price = 60.00,
  size = '4 fl oz / 118ml',
  key_ingredients = ARRAY['Hypochlorous Acid (HOCl)', 'Electrolyzed Saline', 'Sodium Hypochlorite'],
  skin_types = ARRAY['sensitive', 'normal', 'dry', 'combination', 'oily'],
  concerns = ARRAY['post-procedure', 'redness', 'acne', 'sensitivity'],
  how_to_use = 'Spray directly onto skin from 6-8 inches away. Allow to air dry—do not rinse or wipe. Use after cleansing and before serums, or throughout the day for calming relief. Post-procedure: spray 2-3 times daily during the first 3-5 days of recovery.',
  pro_tip = 'Keep it in the refrigerator for extra cooling relief. Post-microneedling and post-laser, we spray HYACYN ACTIVE before Restorative HA Serum—the combo is our go-to recovery protocol at both RELUXE locations.',
  faq = '[{"q":"What is hypochlorous acid?","a":"Hypochlorous acid (HOCl) is the same molecule your white blood cells produce naturally to fight bacteria and reduce inflammation. HYACYN ACTIVE delivers it topically in a gentle, pH-balanced spray."},{"q":"Is this safe on freshly treated skin after procedures?","a":"Yes—that''s its primary use. HYACYN ACTIVE provides antimicrobial protection without any rubbing, rinsing, or irritation. Our RELUXE providers recommend it starting immediately after microneedling, laser, and chemical peel treatments."},{"q":"Can I use HYACYN ACTIVE daily for acne or rosacea?","a":"Absolutely. Many of our Hamilton County patients use it daily as a calming, antibacterial mist for acne-prone or rosacea-prone skin. It''s gentle enough for twice-daily use and won''t interfere with other products."},{"q":"Where can I buy Hydrinity products near me in Indiana?","a":"The full Hydrinity line is available at both RELUXE Med Spa locations in Westfield and Carmel, Indiana. We carry HYACYN ACTIVE and send patients home with it after every energy-based treatment."}]'::JSONB,
  staff_picks = '{"westfield":"Our Westfield team''s post-procedure essential. HYACYN ACTIVE + Restorative HA Serum is the recovery combo we send home with every microneedling and laser patient across Hamilton County.","carmel":"The Carmel team keeps HYACYN ACTIVE refrigerated for patients—the cool mist on post-procedure skin is instant relief. Also a daily staple for our rosacea and acne patients."}'::JSONB,
  related_services = ARRAY['microneedling', 'laser-resurfacing', 'chemical-peels', 'acne-treatment']
WHERE slug = 'soothing-recovery-gel';

-- 3. Barrier Repair Cream → HYDRI-C Daily Vitamin C Moisturizer
UPDATE products SET
  slug = 'hydri-c-moisturizer',
  name = 'HYDRI-C Daily Vitamin C Moisturizer',
  subtitle = 'Vitamin C + Deep Hydration',
  short_description = 'Brightening moisturizer that combines stabilized vitamin C with deep hydration for daily protection and radiance.',
  description = 'HYDRI-C Daily Vitamin C Moisturizer is a brightening, hydrating moisturizer by Hydrinity that combines stabilized vitamin C with hyaluronic acid and peptides for daily environmental protection and visible radiance. Unlike traditional vitamin C serums that can irritate sensitive or post-procedure skin, HYDRI-C delivers vitamin C in a moisturizer format that''s gentle, hydrating, and suitable for all skin types—including freshly treated skin once cleared by your provider. Available at RELUXE Med Spa in Westfield and Carmel, Indiana.

HYDRI-C fills a unique gap in the skincare routine: it provides the antioxidant protection of vitamin C with the barrier-supporting hydration of a quality moisturizer. For patients who find pure vitamin C serums like SkinCeuticals CE Ferulic too potent or irritating, HYDRI-C is an excellent alternative that delivers brightening and protection in a more comfortable format. The peptide complex adds firming benefits while the hyaluronic acid base provides all-day hydration. Our Hamilton County patients love it as a morning moisturizer that does double duty—environmental defense and skin-plumping hydration in one step.',
  category = 'hydration',
  image_url = '/images/products/hydrinity/hydri-c.png',
  price = 150.00,
  size = '50ml / 1.7 fl oz',
  key_ingredients = ARRAY['Stabilized Vitamin C', 'Hyaluronic Acid', 'Peptides', 'Vitamin E', 'Niacinamide'],
  skin_types = ARRAY['normal', 'dry', 'combination', 'sensitive'],
  concerns = ARRAY['dullness', 'fine-lines', 'dryness', 'dark-spots'],
  how_to_use = 'Apply a pea-sized amount to face and neck every morning after cleansing and serums. Follow with mineral SPF. Can also be used in the evening as a nourishing moisturizer.',
  pro_tip = 'For patients who find pure vitamin C serums too irritating, HYDRI-C is the perfect gateway—same brightening and protection in a gentler, more hydrating format. Transition to CE Ferulic once your skin builds tolerance.',
  faq = '[{"q":"Is HYDRI-C as effective as a vitamin C serum?","a":"HYDRI-C uses stabilized vitamin C in a moisturizer base, which delivers brightening and antioxidant benefits with less irritation than pure L-ascorbic acid serums. It''s ideal for sensitive skin or patients new to vitamin C. For maximum potency, step up to SkinCeuticals CE Ferulic once your skin is ready."},{"q":"Can I use this after procedures at RELUXE?","a":"Yes, once your provider clears you for active ingredients—typically 5-7 days after most energy-based treatments. HYDRI-C''s gentle formula makes it one of the first vitamin C products you can safely reintroduce."},{"q":"Do I still need a separate moisturizer?","a":"For most skin types, HYDRI-C provides enough hydration on its own during warmer months. In Indiana''s dry winters, layer it over Restorative HA Serum and under a richer cream like Triple Lipid Restore if your skin needs extra moisture."},{"q":"Where can I buy Hydrinity HYDRI-C near me?","a":"HYDRI-C Daily Vitamin C Moisturizer is available at both RELUXE Med Spa locations in Westfield and Carmel, Indiana. Our skincare specialists can help determine if HYDRI-C or a more concentrated vitamin C serum is right for your skin."}]'::JSONB,
  staff_picks = '{"westfield":"Our Westfield team''s vitamin C pick for sensitive patients. HYDRI-C delivers brightening and protection in a gentle moisturizer format that even freshly treated skin can tolerate.","carmel":"The Carmel team recommends HYDRI-C as the gateway to vitamin C for patients who find serums too irritating. Hydrating, brightening, and gentle enough for Hamilton County patients with reactive skin."}'::JSONB,
  related_services = ARRAY['microneedling', 'chemical-peels']
WHERE slug = 'barrier-repair-cream';

-- 4. Post-Treatment Essentials Kit → Restorative Kit
UPDATE products SET
  slug = 'restorative-kit',
  name = 'Restorative Kit',
  subtitle = 'Post-Procedure Recovery Duo',
  short_description = 'Turn-key recovery kit pairing HYACYN ACTIVE mist with Restorative HA Serum for complete post-procedure care.',
  description = 'The Hydrinity Restorative Kit is a curated post-procedure recovery set that pairs HYACYN ACTIVE purifying mist with Restorative HA Serum—the two essential products for comfortable, effective healing after energy-based treatments. This kit eliminates guesswork during the critical first days of recovery, providing gentle antimicrobial cleansing and deep multi-weight hydration in a simple two-step protocol. Available at RELUXE Med Spa in Westfield and Carmel, Indiana.

The Restorative Kit is what our RELUXE providers send home with patients after microneedling, laser resurfacing, and chemical peels. During the first 3-7 days of recovery, traditional cleansers, active ingredients, and even some moisturizers can irritate freshly treated skin. This kit provides everything needed: HYACYN ACTIVE for gentle cleansing and antimicrobial protection, followed by Restorative HA Serum for deep, multi-level hydration that supports natural healing. The combination keeps healing skin clean, hydrated, and comfortable—which directly translates to better treatment outcomes. We offer it as a bundled value at both Hamilton County locations.',
  category = 'hydration',
  image_url = '/images/products/hydrinity/restorative-kit.jpg',
  price = 160.00,
  size = 'Kit: HYACYN ACTIVE + HA Serum',
  key_ingredients = ARRAY['Hypochlorous Acid (HOCl)', 'Multi-Weight Hyaluronic Acid', 'Peptides', 'Aloe Vera'],
  skin_types = ARRAY['normal', 'dry', 'sensitive', 'combination', 'oily'],
  concerns = ARRAY['post-procedure'],
  how_to_use = 'Days 1-7 post-procedure: Step 1—Spray HYACYN ACTIVE generously, let air dry. Step 2—Apply 2-3 drops of Restorative HA Serum to damp skin. Repeat 2-3 times daily during active recovery. Resume regular skincare products as directed by your RELUXE provider.',
  pro_tip = 'Buy the kit before your procedure so it''s waiting at home when you arrive. Post-procedure compliance drops when patients have to shop while healing—having the kit ready means better outcomes.',
  faq = '[{"q":"What''s included in the Restorative Kit?","a":"The kit includes two products: HYACYN ACTIVE purifying mist (4 fl oz) and Restorative HA Serum (30ml). Together they provide the gentle cleansing and deep hydration your skin needs during the first 3-7 days of post-procedure recovery."},{"q":"When should I buy this—before or after my procedure?","a":"Before. Our Westfield and Carmel teams recommend purchasing the Restorative Kit at your pre-procedure appointment so it''s ready at home when you return from treatment. Compliance is everything in recovery."},{"q":"How long does the kit last?","a":"One kit provides approximately 3-4 weeks of post-procedure care when used as directed. Most patients transition back to their regular skincare routine within 5-7 days, so one kit is typically sufficient per treatment."},{"q":"Where can I get this post-procedure kit near me?","a":"The Hydrinity Restorative Kit is available at both RELUXE Med Spa locations in Westfield and Carmel, Indiana. Ask your provider to include it when booking your next microneedling, laser, or peel treatment."}]'::JSONB,
  staff_picks = '{"westfield":"We send every microneedling and laser patient home with this kit from our Westfield clinic. Two products, zero guesswork—the recovery combo that leads to better outcomes across Hamilton County.","carmel":"The Carmel team bundles the Restorative Kit with every energy-based treatment. Patients who follow the HYACYN + HA protocol heal faster and more comfortably—it''s non-negotiable post-procedure care."}'::JSONB,
  related_services = ARRAY['microneedling', 'laser-resurfacing', 'chemical-peels']
WHERE slug = 'post-treatment-essentials-kit';

-- 5. Replenishing Cleanser → PRELUDE Facial Treatment Cleanser
UPDATE products SET
  slug = 'prelude-cleanser',
  name = 'PRELUDE Facial Treatment Cleanser',
  subtitle = 'Gentle Gel Treatment Cleanser',
  short_description = 'Gentle gel cleanser that removes impurities while preserving the skin barrier—ideal for post-procedure and sensitive skin.',
  description = 'PRELUDE Facial Treatment Cleanser is a gentle gel cleanser by Hydrinity that removes impurities, makeup, and excess oil without stripping the skin barrier or leaving tightness. Formulated with hyaluronic acid, glycerin, and calming botanicals, it cleanses effectively while actually supporting hydration—a rare quality in a cleanser. Available at RELUXE Med Spa in Westfield and Carmel, Indiana.

The cleanser step is where most skincare routines go wrong. Harsh cleansers strip the lipid barrier, triggering a cascade of dryness, sensitivity, and overproduction of oil that sabotages every product applied afterward. PRELUDE was designed to break this cycle. The gel texture feels refreshing without that squeaky-clean tightness, and the formula preserves the barrier so serums and treatments can work on intact, healthy skin. For post-procedure patients, PRELUDE is typically the first cleanser our RELUXE providers clear—it''s gentle enough for freshly treated skin once the initial HYACYN ACTIVE phase is complete. For daily use, it''s the cleanser patients stick with because it simply doesn''t cause problems.',
  category = 'hydration',
  image_url = '/images/products/hydrinity/prelude-cleanser.png',
  price = 58.00,
  size = '150ml / 5 fl oz',
  key_ingredients = ARRAY['Hyaluronic Acid', 'Glycerin', 'Chamomile Extract', 'Aloe Vera'],
  skin_types = ARRAY['normal', 'dry', 'sensitive', 'combination'],
  concerns = ARRAY['sensitivity', 'dryness', 'post-procedure'],
  how_to_use = 'Massage a small amount onto damp skin morning and evening. Rinse thoroughly with lukewarm water. Pat dry gently—never rub. Follow with serums and moisturizer.',
  pro_tip = 'The cleanser is the most underrated step in any routine. Patients who switch to PRELUDE from harsh cleansers see immediate improvement in redness, sensitivity, and product absorption. Your actives can only work on an intact barrier.',
  faq = '[{"q":"Is PRELUDE gentle enough for post-procedure skin?","a":"Yes. PRELUDE is typically the first cleanser our RELUXE providers clear after the initial HYACYN ACTIVE recovery phase. It''s gentle enough for freshly treated skin and won''t disrupt healing."},{"q":"Will it remove makeup effectively?","a":"PRELUDE removes light-to-moderate makeup, SPF, and daily impurities effectively. For heavy or waterproof makeup, use a micellar water or cleansing balm first, then follow with PRELUDE as your second cleanse."},{"q":"My skin feels tight after cleansing—will PRELUDE fix that?","a":"That tight feeling means your current cleanser is stripping your skin barrier. PRELUDE cleanses without stripping—most patients notice the difference immediately. No tightness, no film, just clean, comfortable skin."},{"q":"Where can I buy Hydrinity cleanser near me in Westfield or Carmel?","a":"PRELUDE Facial Treatment Cleanser is available at both RELUXE Med Spa locations in Westfield and Carmel, Indiana. Our skincare specialists can recommend the full Hydrinity protocol during a complimentary consultation."}]'::JSONB,
  staff_picks = '{"westfield":"The cleanser our Westfield patients stick with permanently. PRELUDE doesn''t strip, doesn''t leave film, doesn''t cause tightness—it just works. The foundation of every good routine across Hamilton County.","carmel":"Our Carmel team''s cleanser recommendation for sensitive and post-procedure skin. Patients who switch to PRELUDE see immediate improvement in redness and product absorption. The unsung hero of the routine."}'::JSONB,
  related_services = ARRAY['microneedling', 'chemical-peels']
WHERE slug = 'replenishing-cleanser';

-- 6. Renewal HA Cream → Renewing HA Serum
UPDATE products SET
  slug = 'renewing-ha-serum',
  name = 'Renewing HA Serum',
  subtitle = 'Anti-Aging HA + Peptide Serum',
  short_description = 'Anti-aging serum combining multi-weight hyaluronic acid with firming peptides for visible plumping and line reduction.',
  description = 'Renewing HA Serum is an anti-aging treatment by Hydrinity that combines multi-weight hyaluronic acid with a potent peptide complex to deliver both immediate plumping and long-term firming. While Restorative HA Serum focuses on recovery and hydration, Renewing HA Serum is the daily anti-aging counterpart—designed for patients who want visible reduction in fine lines, improved firmness, and a plumper, more youthful complexion. Available at RELUXE Med Spa in Westfield and Carmel, Indiana.

Renewing HA Serum works on two timelines. The multi-weight hyaluronic acid delivers immediate visible plumping—fine lines look softer from the first application. Over weeks, the peptide complex stimulates collagen production for lasting structural improvement. This dual-action approach makes it particularly effective for mature skin types and anyone noticing loss of firmness, volume, or resilience. For our Hamilton County patients, it layers perfectly under any moisturizer and pairs well with retinoids at night or antioxidant serums in the morning. Indiana''s dry winters accelerate the visible signs of dehydration aging—Renewing HA Serum fights back with deep, sustained hydration that keeps skin looking plump and firm year-round.',
  category = 'anti-aging',
  image_url = '/images/products/hydrinity/renewing-ha-serum.jpg',
  price = 140.00,
  size = '30ml / 1 fl oz',
  key_ingredients = ARRAY['Multi-Weight Hyaluronic Acid', 'Peptide Complex', 'Panthenol', 'Vitamin E'],
  skin_types = ARRAY['normal', 'dry', 'combination', 'sensitive'],
  concerns = ARRAY['fine-lines', 'dryness', 'firmness'],
  how_to_use = 'Apply 2-3 drops to clean, damp skin morning and evening. Follow with moisturizer. Can be layered under retinoids at night or antioxidant serums in the morning.',
  pro_tip = 'Restorative HA is for recovery and hydration; Renewing HA is for anti-aging and firming. Some patients use both—Restorative after procedures and Renewing as their daily anti-aging hydrator.',
  faq = '[{"q":"What''s the difference between Restorative HA and Renewing HA?","a":"Restorative HA Serum is optimized for post-procedure recovery and deep hydration. Renewing HA Serum is the anti-aging counterpart—combining HA with a firming peptide complex for visible plumping and line reduction. Many patients own both."},{"q":"Can I use Renewing HA Serum with retinoids?","a":"Absolutely. Apply Renewing HA Serum to damp skin first, then layer your retinoid (like AlphaRet) over it. The hyaluronic acid creates a hydration buffer that can reduce retinoid irritation while the peptides add anti-aging synergy."},{"q":"How quickly will I see plumping results?","a":"The hyaluronic acid delivers immediate visible plumping from the first application—fine lines look softer within minutes. The peptide-driven firming benefits build over 4-8 weeks of consistent use."},{"q":"Where can I get anti-aging treatments near me in Hamilton County?","a":"RELUXE Med Spa offers comprehensive anti-aging programs at both our Westfield and Carmel locations. Renewing HA Serum is part of our at-home anti-aging protocol, paired with in-clinic treatments like microneedling, Botox, and laser resurfacing."}]'::JSONB,
  staff_picks = '{"westfield":"Our Westfield team''s daily anti-aging hydrator. Renewing HA delivers immediate plumping plus long-term firming from peptides—the serum that makes Hamilton County patients look rested even when they''re not.","carmel":"The Carmel team layers Renewing HA under retinoids at night for maximum anti-aging synergy. Patients see softer fine lines from day one, with compounding firmness improvement over weeks."}'::JSONB,
  related_services = ARRAY['botox', 'microneedling', 'filler']
WHERE slug = 'renewal-ha-cream';


-- ============================================================
-- UNIVERSKIN — Image + Rich Content Updates
-- ============================================================

-- All Universkin products use the same P Serum bottle image
-- since they are personalized formulas in identical packaging

-- 1. P Serum + Niacinamide (NIA)
UPDATE products SET
  image_url = '/images/products/universkin/p-serum.png',
  price = 165.00,
  size = '30ml / 1 fl oz',
  description = 'P Serum + Niacinamide (NIA) is a personalized serum by Universkin where your RELUXE provider selects the exact niacinamide concentration based on your unique skin assessment. Niacinamide is one of the most versatile active ingredients in dermatology—it balances oil production, strengthens the skin barrier, reduces redness, minimizes pore appearance, and improves overall skin texture. Because Universkin allows custom concentrations, your serum is precisely calibrated to your skin''s needs—not a one-size-fits-all formula. Available exclusively at RELUXE Med Spa in Westfield and Carmel, Indiana.

What makes Universkin fundamentally different from off-the-shelf skincare is the personalization. Your RELUXE provider analyzes your skin, identifies your specific concerns, and selects the active ingredients and concentrations that will address them most effectively. Niacinamide is the foundation of most Universkin blends because it plays well with nearly every other active—it can be combined with retinol for anti-aging, azelaic acid for redness, or tranexamic acid for pigmentation. The result is a serum that''s designed specifically for your face, your concerns, and your goals.',
  faq = '[{"q":"How does Universkin personalization work?","a":"Your RELUXE provider conducts a thorough skin analysis, then selects from 19 active ingredients at custom concentrations to create your unique formula. The serum is blended specifically for you—no two formulas are exactly the same."},{"q":"Why niacinamide as a base ingredient?","a":"Niacinamide is the most versatile active in professional skincare—it regulates oil, strengthens the barrier, reduces redness, minimizes pores, and fades discoloration. It also enhances the performance of other actives, making it the ideal foundation for a multi-ingredient custom blend."},{"q":"Can I get my Universkin formula adjusted over time?","a":"Absolutely. As your skin improves or your concerns change, your RELUXE provider can reformulate your serum with different actives or adjusted concentrations. This adaptability is one of Universkin''s greatest strengths."},{"q":"Where can I get personalized skincare near me in Indiana?","a":"Universkin personalized serums are available exclusively through trained providers. Visit RELUXE Med Spa in Westfield or Carmel for a skin analysis and your custom formula—it''s the most personalized skincare available in Hamilton County."}]'::JSONB,
  staff_picks = '{"westfield":"The foundation of almost every custom Universkin blend at our Westfield clinic. Niacinamide is the ultimate team player—it enhances every other active while providing its own powerful benefits for oil balance and barrier support.","carmel":"Our Carmel providers start most Universkin formulas with niacinamide because it works beautifully with every other active ingredient. It''s the versatile base that makes personalized skincare possible."}'::JSONB,
  related_services = ARRAY['skin-consultation']
WHERE slug = 'p-serum-niacinamide';

-- 2. P Serum + Azelaic Acid (AZA)
UPDATE products SET
  image_url = '/images/products/universkin/p-serum.png',
  price = 165.00,
  size = '30ml / 1 fl oz',
  description = 'P Serum + Azelaic Acid (AZA) is a personalized serum by Universkin featuring provider-selected azelaic acid concentration for targeted treatment of redness, rosacea, congestion, and post-inflammatory pigmentation. Azelaic acid is one of the few active ingredients with proven efficacy across multiple skin concerns—it reduces inflammation, kills acne-causing bacteria, inhibits melanin production, and normalizes keratinization. Available exclusively at RELUXE Med Spa in Westfield and Carmel, Indiana.

Azelaic acid is uniquely valuable because it addresses both rosacea and acne in a single ingredient—two conditions that often coexist and require careful management. Unlike harsh acne treatments that can trigger rosacea flares, azelaic acid calms inflammation while clearing pores. The Universkin platform allows your RELUXE provider to select the optimal concentration for your skin—higher percentages for stubborn acne and congestion, moderate concentrations for rosacea and sensitivity maintenance. This customization is especially important for Hamilton County patients dealing with Indiana''s seasonal triggers—humidity-driven breakouts in summer, cold-weather rosacea flares in winter.',
  faq = '[{"q":"Is azelaic acid effective for rosacea?","a":"Yes—azelaic acid is one of the few ingredients with clinical evidence for both rosacea and acne. It reduces redness, calms inflammation, and normalizes skin without the irritation that many other actives cause. Our RELUXE providers customize the concentration based on your rosacea severity."},{"q":"Can azelaic acid help with dark spots from acne?","a":"Absolutely. Azelaic acid inhibits melanin production, making it effective for post-inflammatory hyperpigmentation (the dark marks acne leaves behind). It''s one of the most useful dual-purpose ingredients for acne-prone skin with pigmentation concerns."},{"q":"What concentration of azelaic acid will my serum contain?","a":"Your RELUXE provider determines the optimal concentration based on your skin analysis. Universkin offers a range of concentrations that can be adjusted over time as your skin responds and improves."},{"q":"Where can I get rosacea treatment near me in Westfield or Carmel?","a":"RELUXE Med Spa offers comprehensive rosacea management at both Hamilton County locations. Universkin P Serum + Azelaic Acid is part of our at-home rosacea protocol, paired with Colorescience All Calm SPF and in-clinic BBL or vascular laser treatments."}]'::JSONB,
  staff_picks = '{"westfield":"Our Westfield team''s Universkin pick for rosacea and breakout-prone skin. Azelaic acid calms and clears simultaneously—critical for Indiana patients whose skin reacts to seasonal humidity and temperature swings.","carmel":"The Carmel team''s go-to active for patients with redness + acne overlap. Custom-concentration azelaic acid addresses both concerns without triggering flares—something off-the-shelf products can''t do."}'::JSONB,
  related_services = ARRAY['acne-treatment', 'skin-consultation']
WHERE slug = 'p-serum-azelaic-acid';

-- 3. P Serum + Retinol (RET)
UPDATE products SET
  image_url = '/images/products/universkin/p-serum.png',
  price = 165.00,
  size = '30ml / 1 fl oz',
  description = 'P Serum + Retinol (RET) is a personalized serum by Universkin that delivers retinol at a provider-selected concentration tailored to your skin''s tolerance and anti-aging goals. Retinol remains the single most evidence-backed anti-aging ingredient in dermatology—stimulating collagen production, accelerating cell turnover, smoothing fine lines, and refining texture. The Universkin advantage is precision: your RELUXE provider starts you at exactly the right strength and can adjust upward as your skin builds tolerance, avoiding the irritation and peeling that come with one-size-fits-all retinol products. Available exclusively at RELUXE Med Spa in Westfield and Carmel, Indiana.

The biggest reason patients abandon retinol is irritation—and the biggest cause of irritation is starting too strong. Universkin solves this by allowing your provider to prescribe the exact concentration your skin can handle today, then incrementally increase it over time as tolerance builds. This personalized approach means you get retinol''s full anti-aging power without the redness, flaking, and discomfort that derail most people''s retinol journey. For patients who want the most potent retinoid available, your provider can also combine retinol with supporting ingredients like niacinamide (barrier support) or peptides (collagen boost) in the same serum—creating a multi-active formula that no off-the-shelf product can match.',
  faq = '[{"q":"What retinol strength will I start with?","a":"Your RELUXE provider determines the optimal starting concentration based on your skin type, sensitivity level, and prior retinol experience. Most patients start at a moderate concentration and increase gradually over 2-3 months."},{"q":"Is Universkin retinol better than over-the-counter retinol?","a":"The customization is the advantage. Over-the-counter products offer fixed concentrations—too weak for some, too strong for others. Universkin retinol is prescribed at exactly the right strength for your skin and can be adjusted as your tolerance improves."},{"q":"Can I combine retinol with other actives in my Universkin serum?","a":"Yes—that''s one of Universkin''s greatest strengths. Your provider can blend retinol with niacinamide, peptides, or other supporting ingredients in the same serum, creating a multi-active formula tailored to your specific skin goals."},{"q":"Where can I get professional retinol treatment in Hamilton County?","a":"RELUXE Med Spa in Westfield and Carmel offers personalized Universkin retinol protocols. Your provider will assess your skin, select the right starting concentration, and adjust over time for optimal results with minimal irritation."}]'::JSONB,
  staff_picks = '{"westfield":"Our Westfield team''s approach to retinol: start at exactly the right strength and scale up. Universkin retinol avoids the irritation that derails most patients across Hamilton County—because the concentration is prescribed, not guessed.","carmel":"The Carmel team''s personalized retinol for patients who want anti-aging results without the redness and peeling. Combined with niacinamide in the same serum, it''s the most tolerable retinol protocol available."}'::JSONB,
  related_services = ARRAY['microneedling', 'skin-consultation', 'botox']
WHERE slug = 'p-serum-retinol';

-- 4. P Serum + Tranexamic Acid (TA)
UPDATE products SET
  image_url = '/images/products/universkin/p-serum.png',
  price = 165.00,
  size = '30ml / 1 fl oz',
  description = 'P Serum + Tranexamic Acid (TA) is a personalized serum by Universkin that targets melasma and stubborn hyperpigmentation with provider-selected tranexamic acid concentration. Tranexamic acid works differently from traditional brightening agents—it interrupts the UV-triggered signaling pathway that tells melanocytes to produce excess pigment, addressing the root cause of hormonal and sun-induced discoloration rather than just bleaching the surface. Available exclusively at RELUXE Med Spa in Westfield and Carmel, Indiana.

Melasma is one of the most challenging skin conditions to manage because it''s driven by hormones, UV exposure, and heat—factors that are difficult to eliminate entirely. Indiana''s strong summer sun and outdoor lifestyle make melasma particularly persistent for Hamilton County residents. Tranexamic acid has emerged as one of the most effective ingredients for melasma maintenance because it works upstream in the pigmentation pathway, reducing the inflammatory signals that trigger melanin overproduction. Your RELUXE provider can customize the tranexamic acid concentration in your Universkin serum and combine it with other pigment-fighting actives like kojic acid or niacinamide for a multi-pathway approach. This personalized protocol, paired with daily mineral SPF and periodic in-clinic treatments, represents the most comprehensive melasma management available.',
  faq = '[{"q":"How does tranexamic acid treat melasma differently?","a":"Most brightening ingredients work by inhibiting tyrosinase (the enzyme that makes melanin). Tranexamic acid works upstream—it blocks the UV-triggered signals that tell melanocytes to overproduce melanin in the first place. This addresses the root cause of melasma rather than just the symptom."},{"q":"Can I combine tranexamic acid with other pigment correctors?","a":"Yes—your Universkin serum can combine tranexamic acid with kojic acid, niacinamide, or other brightening actives in a single formula. This multi-pathway approach is significantly more effective than any single ingredient alone."},{"q":"How long until I see improvement in my melasma?","a":"Most patients notice visible improvement in overall brightness within 4-6 weeks. Significant reduction in melasma patches typically occurs at 8-12 weeks with consistent daily use plus mineral SPF compliance."},{"q":"Where can I get melasma treatment near me in Indiana?","a":"RELUXE Med Spa offers comprehensive melasma management at both our Westfield and Carmel locations. Your personalized protocol may include Universkin tranexamic acid serum, SkinCeuticals Discoloration Defense, Colorescience Even Up SPF, and in-clinic treatments like IPL or chemical peels."}]'::JSONB,
  staff_picks = '{"westfield":"Our Westfield team''s top pick for melasma patients. Personalized tranexamic acid concentration + daily mineral SPF + periodic IPL at RELUXE is the most complete pigment protocol available in Hamilton County.","carmel":"The Carmel team combines Universkin TA with SkinCeuticals Discoloration Defense for multi-pathway pigment correction. Customized concentration means we can be more aggressive or gentler based on each patient''s skin."}'::JSONB,
  related_services = ARRAY['ipl-photofacial', 'chemical-peels', 'skin-consultation']
WHERE slug = 'p-serum-tranexamic-acid';

-- 5. P Serum + Kojic Acid (KOJ)
UPDATE products SET
  image_url = '/images/products/universkin/p-serum.png',
  price = 165.00,
  size = '30ml / 1 fl oz',
  description = 'P Serum + Kojic Acid (KOJ) is a personalized serum by Universkin that targets stubborn dark spots, sun damage, and post-inflammatory hyperpigmentation with provider-selected kojic acid concentration. Kojic acid is a powerful tyrosinase inhibitor—it blocks the enzyme responsible for melanin production, making it one of the most effective non-hydroquinone brightening agents available. Available exclusively at RELUXE Med Spa in Westfield and Carmel, Indiana.

Dark spots from sun damage, acne scars, and hormonal changes are among the most common complaints our Hamilton County patients bring to RELUXE. Kojic acid provides targeted, measurable lightening of these discolorations without the risks associated with hydroquinone (which can cause paradoxical darkening with long-term use). Your RELUXE provider selects the optimal concentration based on your pigmentation severity and skin sensitivity. For maximum results, kojic acid is often combined with tranexamic acid in the same Universkin serum—creating a dual-pathway formula that addresses pigmentation from two different angles simultaneously.',
  faq = '[{"q":"Is kojic acid safe for long-term use?","a":"Yes—unlike hydroquinone, which should only be used in cycles, kojic acid can be used continuously without risk of paradoxical darkening. Your Universkin concentration can be adjusted over time as your pigmentation improves."},{"q":"What types of dark spots does kojic acid treat?","a":"Kojic acid is effective against sun damage spots, post-inflammatory hyperpigmentation (acne scars), age spots, and melasma patches. It works by inhibiting the tyrosinase enzyme that drives melanin production."},{"q":"Can I combine kojic acid with tranexamic acid?","a":"Yes—this is one of the most effective Universkin combinations for stubborn pigmentation. Kojic acid blocks melanin production while tranexamic acid blocks the signals that trigger it. Together they attack pigmentation from two pathways for accelerated results."},{"q":"Where can I get dark spot treatment near me in Hamilton County?","a":"RELUXE Med Spa in Westfield and Carmel offers personalized pigment correction protocols using Universkin custom serums, SkinCeuticals Discoloration Defense, and in-clinic treatments like IPL and chemical peels."}]'::JSONB,
  staff_picks = '{"westfield":"Our Westfield team combines kojic acid with tranexamic acid in a single Universkin serum for the most stubborn pigmentation cases across Hamilton County. Dual-pathway correction that off-the-shelf products can''t match.","carmel":"The Carmel team''s targeted spot treatment. Custom kojic acid concentration means we can be precise—more aggressive on deep sun damage, gentler on post-acne marks—all in one personalized formula."}'::JSONB,
  related_services = ARRAY['ipl-photofacial', 'chemical-peels', 'skin-consultation']
WHERE slug = 'p-serum-kojic-acid';

-- 6. P Serum + Madecassoside (MAD)
UPDATE products SET
  image_url = '/images/products/universkin/p-serum.png',
  price = 165.00,
  size = '30ml / 1 fl oz',
  description = 'P Serum + Madecassoside (MAD) is a personalized serum by Universkin that soothes, calms, and repairs reactive and sensitive skin using provider-selected madecassoside concentration. Derived from Centella asiatica (tiger grass), madecassoside is a powerful anti-inflammatory and wound-healing compound that promotes collagen synthesis, reduces redness, and strengthens the skin barrier. It''s the active of choice for chronically sensitive skin and post-procedure recovery. Available exclusively at RELUXE Med Spa in Westfield and Carmel, Indiana.

Sensitive skin isn''t just uncomfortable—it limits what treatments and products you can use. Madecassoside addresses the root cause of sensitivity by repairing the skin barrier and calming the inflammatory cascade that triggers redness, stinging, and reactivity. For our Hamilton County patients, it''s especially valuable during Indiana''s harsh seasonal transitions when cold, dry winter air followed by humid summer heat can trigger sensitivity flares. Your RELUXE provider can use madecassoside as a standalone calming active or combine it with gentle anti-aging ingredients like peptides and niacinamide to build a multi-benefit formula that improves your skin without provoking it.',
  faq = '[{"q":"What is madecassoside and how does it help sensitive skin?","a":"Madecassoside is a compound derived from Centella asiatica (tiger grass) with powerful anti-inflammatory and wound-healing properties. It calms redness, promotes collagen synthesis, and strengthens the skin barrier—addressing the root cause of chronic sensitivity rather than just masking symptoms."},{"q":"Can I use this after procedures at RELUXE?","a":"Yes—madecassoside is excellent for post-procedure recovery. It promotes healing, reduces inflammation, and supports barrier repair. Your provider may include it in your Universkin formula during the recovery phase after microneedling or laser treatments."},{"q":"Is this the same as Centella asiatica in Korean skincare?","a":"Madecassoside is the most potent active compound extracted from Centella asiatica. While many K-beauty products use Centella broadly, Universkin delivers the specific active compound at a clinical concentration customized to your skin''s needs."},{"q":"Where can I get treatment for sensitive skin near me in Indiana?","a":"RELUXE Med Spa in Westfield and Carmel specializes in managing sensitive and reactive skin. Universkin P Serum + Madecassoside is part of our calming skincare protocol, often combined with Hydrinity recovery products and gentle in-clinic treatments."}]'::JSONB,
  staff_picks = '{"westfield":"Our Westfield team''s go-to for chronically sensitive patients. Madecassoside repairs the barrier and calms reactivity from the inside out—especially valuable during Indiana''s harsh seasonal swings across Hamilton County.","carmel":"The Carmel team blends madecassoside with niacinamide for patients who want anti-aging benefits without triggering their sensitivity. It''s the gentlest path to better skin for reactive Hamilton County complexions."}'::JSONB,
  related_services = ARRAY['microneedling', 'skin-consultation']
WHERE slug = 'p-serum-madecassoside';
